name: Ubuntu

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: APT=1 PYSYM=1 CI=1 MKJOBS=2 ./src/scripts/build_ubuntu.sh
