name: Windows

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3
    - name: Build
      shell: cmd
      run: .\src\scripts\build_ci.bat
